// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtwQKhe_OabjjZFTkq2sxaRUBfrqL9n4c',
    appId: '1:642677587502:web:31938f07ad5e64a81a69bf',
    messagingSenderId: '642677587502',
    projectId: 'webdoc-896a8',
    authDomain: 'webdoc-896a8.firebaseapp.com',
    databaseURL: 'https://webdoc-896a8.firebaseio.com',
    storageBucket: 'webdoc-896a8.appspot.com',
    measurementId: 'G-SHG8Z76VV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY2_N3ab_45ggVlisDcuOWxhbzVZZqN34',
    appId: '1:642677587502:android:15d9c9d071d304d11a69bf',
    messagingSenderId: '642677587502',
    projectId: 'webdoc-896a8',
    databaseURL: 'https://webdoc-896a8.firebaseio.com',
    storageBucket: 'webdoc-896a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ZtyOAV8O6weBXUm__yUIvWdurQDMzvU',
    appId: '1:642677587502:ios:aae4b170822d7ad31a69bf',
    messagingSenderId: '642677587502',
    projectId: 'webdoc-896a8',
    databaseURL: 'https://webdoc-896a8.firebaseio.com',
    storageBucket: 'webdoc-896a8.appspot.com',
    androidClientId: '642677587502-18lu36vnftng78diee8no35p0c3p31ie.apps.googleusercontent.com',
    iosBundleId: 'com.webdoc.health',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4ZtyOAV8O6weBXUm__yUIvWdurQDMzvU',
    appId: '1:642677587502:ios:5db6c536c269b8c31a69bf',
    messagingSenderId: '642677587502',
    projectId: 'webdoc-896a8',
    databaseURL: 'https://webdoc-896a8.firebaseio.com',
    storageBucket: 'webdoc-896a8.appspot.com',
    androidClientId: '642677587502-18lu36vnftng78diee8no35p0c3p31ie.apps.googleusercontent.com',
    iosClientId: '642677587502-b01pnjm339idtig18kfuu1vnu8bs0n2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsAiz9gfjh8LQMT0_x46htzDvJx1j60a0',
    appId: '1:642677587502:web:386e1d92a819f2131a69bf',
    messagingSenderId: '642677587502',
    projectId: 'webdoc-896a8',
    authDomain: 'webdoc-896a8.firebaseapp.com',
    databaseURL: 'https://webdoc-896a8.firebaseio.com',
    storageBucket: 'webdoc-896a8.appspot.com',
    measurementId: 'G-56NHSNKW1H',
  );

}